export const NFT_CONTRACT = "0x69605491147DD002E68650aD32d6d1ba87D42e0A";

export const CORE_ABI = [
  {
    inputs: [
      { name: "thetaBaseURI", internalType: "string", type: "string" },
      { name: "betaBaseURI", internalType: "string", type: "string" },
      { name: "alphaBaseURI", internalType: "string", type: "string" },
      { name: "sigmaBaseURI", internalType: "string", type: "string" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        indexed: true,
        name: "owner",
        internalType: "address",
        type: "address",
      },
      {
        indexed: true,
        name: "approved",
        internalType: "address",
        type: "address",
      },
      {
        indexed: true,
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "Approval",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: true,
        name: "owner",
        internalType: "address",
        type: "address",
      },
      {
        indexed: true,
        name: "operator",
        internalType: "address",
        type: "address",
      },
      { indexed: false, name: "approved", internalType: "bool", type: "bool" },
    ],
    name: "ApprovalForAll",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      { indexed: true, name: "user", internalType: "address", type: "address" },
      {
        indexed: true,
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "timestamp",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "NFTBurned",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      { indexed: true, name: "user", internalType: "address", type: "address" },
      {
        indexed: true,
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "category",
        internalType: "enum DailyNFTRewards.NFTCategory",
        type: "uint8",
      },
      {
        indexed: false,
        name: "timestamp",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "NFTClaimed",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: true,
        name: "previousOwner",
        internalType: "address",
        type: "address",
      },
      {
        indexed: true,
        name: "newOwner",
        internalType: "address",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      { indexed: true, name: "from", internalType: "address", type: "address" },
      { indexed: true, name: "to", internalType: "address", type: "address" },
      {
        indexed: true,
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "Transfer",
    anonymous: false,
    type: "event",
  },
  {
    outputs: [],
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "approve",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "balanceOf",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "burnAndUnlock",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [],
    name: "claimNFT",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "getApproved",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256[]", type: "uint256[]" }],
    inputs: [{ name: "user", internalType: "address", type: "address" }],
    name: "getBurnHistory",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256[]", type: "uint256[]" }],
    inputs: [{ name: "user", internalType: "address", type: "address" }],
    name: "getClaimHistory",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "user", internalType: "address", type: "address" }],
    name: "getLastClaimedTime",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [
      {
        name: "",
        internalType: "enum DailyNFTRewards.NFTCategory",
        type: "uint8",
      },
    ],
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "getNFTCategory",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [
      { name: "owner", internalType: "address", type: "address" },
      { name: "operator", internalType: "address", type: "address" },
    ],
    name: "isApprovedForAll",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "string", type: "string" }],
    inputs: [],
    name: "name",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [],
    name: "owner",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "ownerOf",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [],
    name: "renounceOwnership",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "safeTransferFrom",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
      { name: "data", internalType: "bytes", type: "bytes" },
    ],
    name: "safeTransferFrom",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "operator", internalType: "address", type: "address" },
      { name: "approved", internalType: "bool", type: "bool" },
    ],
    name: "setApprovalForAll",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      {
        name: "category",
        internalType: "enum DailyNFTRewards.NFTCategory",
        type: "uint8",
      },
      { name: "baseURI", internalType: "string", type: "string" },
    ],
    name: "setCategoryBaseURI",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [{ name: "interfaceId", internalType: "bytes4", type: "bytes4" }],
    name: "supportsInterface",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "string", type: "string" }],
    inputs: [],
    name: "symbol",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "string", type: "string" }],
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "tokenURI",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "transferFrom",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    stateMutability: "nonpayable",
    type: "function",
  },
];
